# Generated by Django 4.0 on 2021-12-17 20:28

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1200)),
                ('authors', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddIndex(
            model_name='bookmodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='BookIndex'),
        ),
    ]
