# Generated by Django 4.0 on 2021-12-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_cityl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityl',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Cityl',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
